<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewVote.aspx.cs" Inherits="WebApplication3.ViewVote" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title> VIEW VOTE </title>
    <style>
        .d2
        {
            height:300px;
            width:700px;
            margin-left:492px;
            background-color:rgb(0,0,0,0.3);
            border-radius:27px;

        }
    </style>
</head>
<body  style="background-image:url(images/picture.jpg); background-repeat:no-repeat; background-size:cover; " >
    <form id="form1" runat="server">
       <div>
             <h2 style="font-size:35px; text-align:center; color:darkblue; "> <b> HELLO ADMIN , FROM HERE YOU CAN MANAGE THE VOTERS  </b></h2>
        </div>
    <p style="font-size:30px;" >
         From here you can 
         :-&nbsp; 
   </p>
    <ul style="font-size:25px;">
  <li><b> VIEW THE VOTER <br /></b></li>
        
       
  <li><b> UPDATE THE VOTER <br /></b></li>
        <li><b>DELETE THE VOTER<br /> </b></li>
</ul>
    <div class="d2">
        <br />
        <br />


        <center><asp:GridView ID="GridView1" runat="server" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" Height="210px" Width="346px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
            <AlternatingRowStyle BackColor="White" />
            <FooterStyle BackColor="#CCCC99" />
            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#F7F7DE" />
            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FBFBF2" />
            <SortedAscendingHeaderStyle BackColor="#848384" />
            <SortedDescendingCellStyle BackColor="#EAEAD3" />
            <SortedDescendingHeaderStyle BackColor="#575357" />
        </asp:GridView> </center>
    </div>
    </form>
    </body>
</html>
